"""Phase 13: research decision-support layer (margin-based uncertainty path).

Builds a deterministic, structured, research-only presentation of the frozen
Phase 9 E1 Dual Attention MIL model outputs:

    prediction (fixed 0.5 threshold)
    + malignant-class model score (NOT calibrated)
    + margin-based uncertainty flag (proximity to the threshold ONLY)
    + top-k model-attribution evidence (Phase 11 semantics)
    + cross_modal_evidence = UNAVAILABLE (Phase 12 outcome)
    + suggested_action = "Clinical review recommended" (research safety flag)
    + mandatory research-only disclaimer

Hard safety boundaries (owner-approved Phase 13 scope):
    * This is NOT a clinical diagnostic system and NOT clinical risk
      stratification. The score is a raw, uncalibrated model output.
    * NO calibration of any kind is performed (no Platt/temperature/isotonic
      scaling, no conformal prediction); the score is never presented as a
      calibrated clinical probability.
    * The uncertainty flag reflects |score - 0.5| <= margin ONLY. It is NOT
      clinical/diagnostic uncertainty and NOT patient/cancer risk.
    * Top-k evidence rows are model-attributed image instances (Phase 11
      semantics); they are NOT tumor/cancer/lesion regions and NOT clinical
      explanations. Model Attention != Clinical Explanation.
    * cross_modal_evidence is hard-coded UNAVAILABLE for every output
      (Phase 12: NOT CURRENTLY FEASIBLE). No MRI imports, no MRI data, no
      synthetic MRI, no concordant/discordant values are ever produced.
    * suggested_action is the fixed research safety flag "Clinical review
      recommended" — never treatment advice, triage, referral, or diagnosis.
    * Filename-derived source keys are grouping identifiers, NOT patient/
      study/lesion identifiers, and are never presented as such.

Data safety: reads frozen artifacts only (E1 checkpoint, Phase 5.5 bag
interface, Phase 11 attribution helpers, frozen persisted predictions).
No training, no optimizer, no checkpoint/manifest modification, no
test-set inference, no threshold fitting on any split (threshold 0.5 and
margin 0.1 are pre-registered constants from Phases 9/10/11).
"""
from __future__ import annotations

import hashlib
from typing import Any, Dict, List, Optional, Sequence

# Reuse the authoritative Phase 11 attribution helpers verbatim (deterministic
# ranking, tie-breaking, k>n clamping) rather than duplicating their logic.
from src.explainability.attention_visualization import (  # noqa: E402
    extract_bag_attention,
    rank_instances,
    top_k_instances,
    verify_checkpoint_md5,
)

# ---------------------------------------------------------------------------
# Pre-registered constants (NOT fitted on any split; Phase 9/10/11 heritage)
# ---------------------------------------------------------------------------

DECISION_THRESHOLD = 0.5          # frozen E1 decision threshold (Phase 9)
UNCERTAINTY_MARGIN = 0.1          # Phase 10/11 uncertainty-margin convention
DEFAULT_TOP_K = 3                 # deterministic, fixed a priori
E1_CHECKPOINT_MD5 = "258710649fb0e6979f64fc1e7ccfc28f"
E1_CHECKPOINT_RELPATH = "model/dual_attention/da_stage_b/best.pt"
SOURCE_KEY_STATUS = "inferred_from_filename_not_verified_identifier"

SUGGESTED_ACTION = "Clinical review recommended"
CROSS_MODAL_EVIDENCE = "UNAVAILABLE"   # hard-coded; Phase 12 outcome

RESEARCH_ONLY_DISCLAIMER = (
    "RESEARCH PROTOTYPE - NOT CLINICALLY VALIDATED. This output is generated by "
    "an experimental research model on an identifier-free ultrasound dataset. "
    "The malignant_class_model_score is a raw, UNCALIBRATED model output, not a "
    "calibrated clinical probability, and the uncertainty_flag reflects only the "
    "model score's proximity to the fixed 0.5 decision threshold - it is not "
    "clinical or diagnostic uncertainty and not patient or cancer risk. Model "
    "attention and Grad-CAM are model attribution mechanisms, not clinical "
    "explanations (Model Attention != Clinical Explanation), and are not "
    "validated as lesion localization. No MRI/cross-modal evidence is available "
    "(Phase 12). This output must NOT be used as a diagnosis, a clinical risk "
    "assessment, or a treatment recommendation, and does not replace radiologist "
    "or pathologist judgment."
)

# Fixed output field order (schema contract; T13-05 asserts exact key set)
OUTPUT_FIELDS = (
    "prediction",
    "malignant_class_model_score",
    "prediction_confidence",
    "uncertainty_flag",
    "uncertainty_margin",
    "top_k_evidence",
    "cross_modal_evidence",
    "suggested_action",
    "research_only_disclaimer",
    "provenance",
)


# ---------------------------------------------------------------------------
# threshold mapping (frozen 0.5; never fitted/tuned on any split)
# ---------------------------------------------------------------------------

def prediction_from_score(score: float) -> int:
    """Map a model score to the frozen-threshold prediction.

    ``score < 0.5 -> 0 (Benign model prediction)``;
    ``score >= 0.5 -> 1 (Malignant model prediction)``.
    The threshold is the pre-registered Phase 9 constant 0.5 and is never
    fitted or tuned on any split (in particular, never on the test set).
    """
    return 1 if float(score) >= DECISION_THRESHOLD else 0


def prediction_label(prediction: int) -> str:
    """Human-readable label for the model prediction (explicitly a *model*
    prediction, not a diagnosis)."""
    return "Malignant model prediction" if int(prediction) == 1 else "Benign model prediction"


# ---------------------------------------------------------------------------
# margin-based uncertainty flag (proximity to the threshold ONLY)
# ---------------------------------------------------------------------------

def uncertainty_flag_from_score(score: float, margin: float = UNCERTAINTY_MARGIN) -> bool:
    """Pre-registered margin rule: uncertain iff |score - 0.5| <= margin.

    This expresses model-score proximity to the decision threshold only.
    Boundary behaviour (documented and tested): scores exactly at the margin
    edges (|score-0.5| == margin, e.g. 0.4/0.6) ARE flagged uncertain; scores
    strictly beyond the margin are not. Float representation is handled with
    an exact-decimal tolerance of 1e-9 so that 0.4/0.6 land on the intended
    side deterministically regardless of binary floating-point error.
    """
    distance = abs(float(score) - DECISION_THRESHOLD)
    return distance <= float(margin) + 1e-9


def confidence_label(score: float) -> str:
    """Descriptive confidence wording derived from the margin rule.

    'high' when the score lies strictly beyond the uncertainty margin from the
    threshold, 'borderline (within uncertainty margin)' otherwise. This is a
    model-confidence description only — never clinical certainty.
    """
    return ("borderline (within uncertainty margin)" if uncertainty_flag_from_score(score)
            else "high")


# ---------------------------------------------------------------------------
# evidence assembly (Phase 11 attribution semantics, verbatim helpers)
# ---------------------------------------------------------------------------

def _top_k_evidence(attention: Sequence[float],
                    k: int = DEFAULT_TOP_K,
                    batch: Optional[Any] = None) -> List[Dict[str, Any]]:
    """Top-k model-attributed image instances for one bag.

    Uses the Phase 11 :func:`top_k_instances` helper verbatim: deterministic
    descending attention order, ties broken by ascending instance order,
    ``k > n`` safely clamps to ``n``. Rows are extended with ``image_path``
    and ``md5`` provenance when a Phase 5.5 loader batch (with an instances
    table) is supplied. Rows describe MODEL ATTRIBUTION only — never tumor/
    cancer/lesion regions and never clinical explanations.
    """
    rows = top_k_instances(attention, k)
    evidence: List[Dict[str, Any]] = []
    for row in rows:
        item = {
            "order_index": int(row["order_index"]),
            "attention": float(row["attention"]),
            "rank": int(row["rank"]),
            "semantics": "model-attributed image instance (attention weight); "
                         "not a tumor/cancer/lesion region and not a clinical explanation",
        }
        if batch is not None:
            instances = getattr(batch, "instances", None) or []
            idx = int(row["order_index"])
            if 0 <= idx < len(instances):
                inst = instances[idx]
                img = getattr(inst, "image_path", None) or inst.get("image_path")
                md5 = getattr(inst, "md5", None) or inst.get("md5")
                if img is not None:
                    item["image_path"] = str(img)
                if md5 is not None:
                    item["md5"] = str(md5)
        evidence.append(item)
    return evidence


# ---------------------------------------------------------------------------
# main entry point: structured decision-support record for one bag
# ---------------------------------------------------------------------------

def build_decision_support_record(score: float,
                                  attention: Sequence[float],
                                  *,
                                  bag_id: Optional[str] = None,
                                  source_group_id: Optional[str] = None,
                                  split: Optional[str] = None,
                                  top_k: int = DEFAULT_TOP_K,
                                  batch: Optional[Any] = None,
                                  checkpoint_md5: Optional[str] = None) -> Dict[str, Any]:
    """Assemble the deterministic Phase 13 decision-support record for one bag.

    Parameters map 1:1 to frozen artifacts: ``score`` is the frozen E1 bag
    probability (already persisted in the Phase 9 prediction CSVs; no new
    inference is required), ``attention`` is the bag's frozen stage-2
    attention vector (Phase 11 export / re-extractable via the frozen model).
    The record is a pure function of its inputs — no global state, no
    randomness, no I/O beyond the optional batch provenance lookup.
    """
    score_f = float(score)
    prediction = prediction_from_score(score_f)
    uncertain = uncertainty_flag_from_score(score_f)
    evidence = _top_k_evidence(attention, k=top_k, batch=batch)

    provenance = {
        "model": "E1 Dual Attention MIL (da_stage_b)",
        "checkpoint_relpath": E1_CHECKPOINT_RELPATH,
        "checkpoint_md5": checkpoint_md5 or verify_checkpoint_md5(),
        "decision_threshold": DECISION_THRESHOLD,
        "score_is_calibrated": False,
        "uncertainty_rule": f"abs(score - {DECISION_THRESHOLD}) <= {UNCERTAINTY_MARGIN} "
                            "(model-score proximity to the decision threshold only)",
        "attribution_source": "Phase 11 stage-2 MIL attention (model attribution)",
        "source_key_status": SOURCE_KEY_STATUS,
        "attribution_note": "Model Attention != Clinical Explanation",
    }
    if bag_id is not None:
        provenance["bag_id"] = str(bag_id)
    if source_group_id is not None:
        provenance["source_group_id"] = str(source_group_id)
        provenance["source_group_id_note"] = (
            "filename-derived grouping identifier; NOT a patient/study/lesion identifier")
    if split is not None:
        provenance["split"] = str(split)

    record = {
        "prediction": prediction_label(prediction),
        "malignant_class_model_score": score_f,
        "prediction_confidence": confidence_label(score_f),
        "uncertainty_flag": bool(uncertain),
        "uncertainty_margin": UNCERTAINTY_MARGIN,
        "top_k_evidence": evidence,
        "cross_modal_evidence": CROSS_MODAL_EVIDENCE,
        "suggested_action": SUGGESTED_ACTION,
        "research_only_disclaimer": RESEARCH_ONLY_DISCLAIMER,
        "provenance": provenance,
    }
    assert set(record) == set(OUTPUT_FIELDS), "decision-support schema drifted"
    return record


def build_records_from_scores(scores: Dict[str, float],
                              attention_by_bag: Dict[str, Sequence[float]],
                              *,
                              meta_by_bag: Optional[Dict[str, dict]] = None,
                              top_k: int = DEFAULT_TOP_K,
                              checkpoint_md5: Optional[str] = None) -> Dict[str, Dict[str, Any]]:
    """Build decision-support records for many bags (e.g. a frozen prediction CSV).

    ``scores`` maps bag_id -> malignant-class model score (from the frozen
    Phase 9 persisted predictions); ``attention_by_bag`` maps bag_id -> the
    bag's stage-2 attention vector. ``meta_by_bag`` optionally supplies
    ``source_group_id`` / ``split`` per bag. Output is keyed by bag_id with
    ascending bag-id iteration for deterministic ordering.
    """
    out: Dict[str, Dict[str, Any]] = {}
    meta_by_bag = meta_by_bag or {}
    for bag_id in sorted(scores):
        meta = meta_by_bag.get(bag_id, {})
        attention = attention_by_bag.get(bag_id, [])
        rec = build_decision_support_record(
            scores[bag_id],
            attention,
            bag_id=bag_id,
            source_group_id=meta.get("source_group_id"),
            split=meta.get("split"),
            top_k=top_k,
            checkpoint_md5=checkpoint_md5,
        )
        # Attention export coverage is Phase 11's train/val selected-case set;
        # bags without export rows still get complete records (empty evidence).
        rec["provenance"]["attention_available"] = bool(attention)
        out[bag_id] = rec
    return out


def md5_of_file(path: str) -> str:
    """Small provenance helper (file MD5) used by tests and reports."""
    with open(path, "rb") as fh:
        return hashlib.md5(fh.read()).hexdigest()


__all__ = [
    "DECISION_THRESHOLD",
    "UNCERTAINTY_MARGIN",
    "DEFAULT_TOP_K",
    "E1_CHECKPOINT_MD5",
    "E1_CHECKPOINT_RELPATH",
    "SOURCE_KEY_STATUS",
    "SUGGESTED_ACTION",
    "CROSS_MODAL_EVIDENCE",
    "RESEARCH_ONLY_DISCLAIMER",
    "OUTPUT_FIELDS",
    "prediction_from_score",
    "prediction_label",
    "uncertainty_flag_from_score",
    "confidence_label",
    "build_decision_support_record",
    "build_records_from_scores",
    "extract_bag_attention",
    "rank_instances",
    "top_k_instances",
    "verify_checkpoint_md5",
    "md5_of_file",
]
